### ISSUE TITLE
rspec cannot read path

### ISSUE THREAD

**Issue by B0tt92** [learn-co-curriculum/phase-0-css-intro-lab#7]
### Canvas Link

https://learning.flatironschool.com/courses/4605/assignments/141141?module_item_id=294978

### Concern

when rspec is run it does not recognize the file path, but opening the link with CRTL +     
Click opens the .css. Edge page will also open the HTML with the stylesheet. 

<meta charset="utf-8">
    <title>Introduction to CSS Lab</title>
     
    <link rel="stylesheet" href="./style.CSS" /> 
    
  </head>

### Additional Context

bott@LAPTOP-:/mnt/c/development/code/phase-0-css-intro-lab$ rspec
..F

Failures:

  1) styling within index.html correctly links to the style.css file with a relative path
     Failure/Error: expect(link.attributes["href"]).to match(/\.\/style\.css/), "Make sure you provide a relative path to style.css from index.html"

       Make sure you provide a relative path to style.css from index.html
       Diff:
       @@ -1,2 +1,2 @@
       -/\.\/style\.css/
       +#(Attr:0xb18 { name = "href", value = "./style.CSS" })

     # ./spec/css_spec.rb:26:in `block (3 levels) in <top (required)>'

Finished in 0.18253 seconds (files took 0.43345 seconds to load)
3 examples, 1 failure

Failed examples:

rspec ./spec/css_spec.rb:22 # styling within index.html correctly links to the style.css file with a relative path

**Comment by ihollander** [comment]
Hi @B0tt92, I went into this lesson and it looks like the `rspec` tests are behaving as expected. For assistance with the labs passing the labs, please reach use the `#js-prework-support` channel rather than raising an issue. Issues should only be used when there is a bug in the lesson code or some other problem with a lesson.

For some more information on your particular issue, the tests are often looking for very specific values, so even little things like punctuation and capitalization will cause the tests to fail. 

For example, looking at the output from `rspec`:

```txt
Make sure you provide a relative path to style.css from index.html
Diff:
@@ -1,2 +1,2 @@
-/./style.css/
+#(Attr:0xb18 { name = "href", value = "./style.CSS" })
```

It would appear that your `<link>` element has a `href` attribute with a value of `./style.CSS` (with CSS in caps) whereas the spec is looking for `./style.css` (not in caps).

Best of luck with the rest of the prework!
